basePath: /api/v1
definitions:
  models.Echo:
    properties:
      id:
        type: string
      message:
        type: string
    type: object
host: localhost:8082
info:
  contact:
    email: support@swagger.io
    name: Sai Kris
    url: http://www.swagger.io/support
  description: This is a simple REST API written in Golang to demonstrate it's simplicity.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Web API written in Golang
  version: "1.0"
paths:
  /echos:
    get:
      description: Simulates a slow echo request.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/models.Echo'
        "400": {}
        "404": {}
        "500": {}
      summary: Get echo messages.
swagger: "2.0"
